name: Validar CSS

on:
  push:
    branches:
      - main

jobs:
  validar-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Validar CSS con W3C
        uses: docker://ghcr.io/mirkoledda/w3c-css-validator:latest
        with:
          args: css/*.css
