name: Validar CSS

on:
  push:
    branches:
      - main

jobs:
  validar-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Validar style.css con W3C
        run: |
          echo "Validando css/style.css"
          curl -s -F "file=@css/style.css;type=text/css" https://jigsaw.w3.org/css-validator/validator --output result.html
          if grep -q "Sorry! We found the following errors" result.html; then
            echo "❌ Errores encontrados en style.css"
            cat result.html
            exit 1
          else
            echo "✅ style.css válido"
          fi
